version: '2'
services:
    jhipster-app:
        image: jhipster
        external_links:
            - jhipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
#            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/feedme
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    feedme-postgresql:
        extends:
            file: postgresql.yml
            service: feedme-postgresql
#    jhipster-mysql:
#        extends:
#            file: mysql.yml
#            service: jhipster-mysql
